{{--
    Automated Legal and Institutional PDF Case Exporter - the PDF itself.
    Module 3 feature owner: Johra-E-Jannat Oishy.

    DomPDF only understands a subset of CSS: no flexbox, no grid, no
    `gap`. Layout here is deliberately table/block based, and the font is
    DejaVu Sans - DomPDF's docs specifically warn that core fonts like
    Helvetica aren't embedded and can fail validation, DejaVu is bundled
    and safe.
--}}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #1a1a1a; }

    .header { text-align: center; border-bottom: 2px solid #DC143C; padding-bottom: 10px; margin-bottom: 20px; }
    .header h1 { font-size: 18px; margin: 0 0 4px 0; }
    .header p { margin: 0; font-size: 11px; color: #555555; }

    .disclaimer { font-size: 10px; color: #666666; font-style: italic; margin: 0 0 20px 0; line-height: 1.5; }

    table.meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    table.meta-table td { padding: 4px 6px; border: 1px solid #dddddd; font-size: 11px; }
    table.meta-table td.label { font-weight: bold; width: 140px; background-color: #f7f7f7; }

    .section-title { font-size: 14px; font-weight: bold; border-bottom: 1px solid #cccccc; padding-bottom: 4px; margin: 20px 0 10px 0; }
    .description { white-space: pre-wrap; line-height: 1.5; }

    table.timeline { width: 100%; border-collapse: collapse; }
    table.timeline th, table.timeline td { border: 1px solid #dddddd; padding: 6px; font-size: 11px; text-align: left; }
    table.timeline th { background-color: #f7f7f7; }

    .footer { margin-top: 30px; font-size: 10px; color: #888888; border-top: 1px solid #dddddd; padding-top: 8px; }
</style>
</head>
<body>
@php
    // event_date/incident_date may arrive as a Carbon instance (Eloquent
    // cast) or a raw DB string (query-builder rows have no casting at
    // all) - normalise either way rather than assuming one or the other.
    $formatDate = function ($value, $format = 'F j, Y') {
        if (empty($value)) {
            return null;
        }
        if ($value instanceof \Illuminate\Support\Carbon) {
            return $value->format($format);
        }
        try {
            return \Illuminate\Support\Carbon::parse($value)->format($format);
        } catch (\Throwable $e) {
            return (string) $value;
        }
    };
@endphp

    <div class="header">
        <h1>CyberGuard Case Report</h1>
        <p>Confidential document generated for official use</p>
    </div>

    <p class="disclaimer">
        This report reflects information submitted directly by the reporting
        individual through the CyberGuard platform. It has not been independently
        investigated or verified and is provided to support, not substitute, the
        recipient's own review process.
    </p>

    <table class="meta-table">
        <tr>
            <td class="label">Tracking Code</td>
            <td>{{ $incident->tracking_id ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Platform</td>
            <td>{{ $incident->platform ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Incident Date</td>
            <td>{{ $formatDate($incident->incident_date ?? null) ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Report Status</td>
            <td>{{ $incident->status ?? 'N/A' }}</td>
        </tr>
    </table>

    @if ($includeDescription && ! empty($incident->description))
        <div class="section-title">Incident Description</div>
        <p class="description">{{ $incident->description }}</p>
    @endif

    @if ($timelineEvents->isNotEmpty())
        <div class="section-title">Timeline of Events</div>
        <table class="timeline">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Behavior</th>
                    <th>Summary</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($timelineEvents as $event)
                    <tr>
                        <td>
                            {{ $formatDate($event->event_date ?? null) }}
                            {{ !empty($event->event_time) ? ' '.$event->event_time : '' }}
                        </td>
                        <td>{{ $event->behavior_type ?? '' }}</td>
                        <td>{{ $event->summary ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by CyberGuard on {{ $generatedAt->format('F j, Y \a\t g:i A') }}.
        Produced at the request of the reporting individual for their own use.
    </div>
</body>
</html>
