@extends('layouts.app')

@section('title', 'Crisis Support Directory | CyberGuard')

@section('content')
<div class="directory-page">
    <div class="container pt-3">
        @include('partials.admin-menu')
    </div>
    <section class="directory-hero">
        <div class="hero-overlay"><div class="container py-5"><p class="eyebrow">Verified support network</p><h1>Crisis Support &amp; Regional Help-Center Directory</h1><p>Add and modify the physical addresses of local crisis clinics, register regional telephone hotlines.</p><a href="{{ route('admin.help-directory.index') }}#directory-form" class="btn btn-crimson"><i class="fas fa-plus me-2"></i>Add new</a></div></div>
    </section>

    <div class="container py-4">
        <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2"><div><p class="eyebrow mb-1">Manual verification desk</p><h2 class="h4 mb-0">Existing locations</h2></div></div>
        @foreach (['success' => 'success', 'error' => 'danger'] as $key => $class)
            @if(session($key))<div class="alert alert-{{ $class }}">{{ session($key) }}</div>@endif
        @endforeach
        @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <div class="row g-3 mb-5">
            @forelse($helpCenters as $center)
                <div class="col-md-6 col-xl-4"><article class="location-card h-100"><div class="d-flex justify-content-between gap-2"><div><span class="type-label">{{ $center->type_label }}</span><h3>{{ $center->name }}</h3></div><span class="status-dot" title="Active"></span></div><p class="address"><i class="fas fa-location-dot me-2"></i>{{ collect([$center->address, $center->city, $center->state, $center->zip_code])->filter()->join(', ') ?: 'No address recorded' }}</p><div class="hotline-list">@forelse($center->hotlines as $hotline)<div><i class="fas fa-phone me-2"></i><strong>{{ $hotline->phone_number }}</strong>@if($hotline->is_toll_free)<span class="mini-tag">Toll free</span>@endif</div>@empty<span class="text-muted small">No hotline registered</span>@endforelse</div><div class="card-actions"><a href="{{ route('admin.help-directory.index', ['edit' => $center->id]) }}#directory-form" class="btn btn-sm btn-outline-dark"><i class="fas fa-pen me-1"></i>Edit</a><form method="POST" action="{{ route('admin.help-directory.destroy', $center) }}" onsubmit="return confirm('Delete this help center and its hotlines?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash me-1"></i>Delete</button></form></div></article></div>
            @empty
                <div class="col-12"><div class="empty-state">No help centers have been registered yet.</div></div>
            @endforelse
        </div>

        @php $editing = $editingCenter; $isEditing = $editing !== null; $workingHours = old('working_hours', $editing?->working_hours ?? []); $formHotlines = old('hotlines', $editing?->hotlines?->map(fn($h) => ['name' => $h->name, 'phone_number' => $h->phone_number, 'is_toll_free' => $h->is_toll_free, 'description' => $h->description, 'operating_hours' => $h->operating_hours ?? []])->toArray() ?? [[]]); if (empty($formHotlines)) $formHotlines = [[]]; @endphp
        <section id="directory-form" class="form-panel"><div class="panel-heading"><div><p class="eyebrow mb-1">{{ $isEditing ? 'Update record' : 'New record' }}</p><h2 class="h4 mb-0">{{ $isEditing ? 'Edit help center' : 'Register a help center' }}</h2></div>@if($isEditing)<a href="{{ route('admin.help-directory.index') }}#directory-form" class="btn btn-sm btn-outline-secondary">Cancel edit</a>@endif</div>
            <form method="POST" action="{{ $isEditing ? route('admin.help-directory.update', $editing) : route('admin.help-directory.store') }}">
                @csrf @if($isEditing) @method('PUT') @endif
            <div class="row g-3 p-4"><div class="col-md-8"><label class="form-label">Help-center name</label><input name="name" class="form-control" required value="{{ old('name', $editing?->name) }}"></div><div class="col-md-4"><label class="form-label">Type</label><select name="type" class="form-select" required><option value="">Select type</option>@foreach($types as $value => $label)<option value="{{ $value }}" @selected(old('type', $editing?->type) === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Help-center street address</label><input name="address" class="form-control" value="{{ old('address', $editing?->address) }}" placeholder="Building, street, landmark"></div><div class="col-md-4"><label class="form-label">Help-center city / region</label><input name="city" class="form-control" required value="{{ old('city', $editing?->city) }}"></div><div class="col-md-4"><label class="form-label">Help-center state / division</label><input name="state" class="form-control" value="{{ old('state', $editing?->state) }}"></div><div class="col-md-4"><label class="form-label">Help-center postal code</label><input name="zip_code" class="form-control" value="{{ old('zip_code', $editing?->zip_code) }}"></div><div class="col-md-6"><label class="form-label">Help-center latitude <span class="text-muted fw-normal">optional</span></label><input name="latitude" type="number" step="any" class="form-control" value="{{ old('latitude', $editing?->latitude) }}"></div><div class="col-md-6"><label class="form-label">Help-center longitude <span class="text-muted fw-normal">optional</span></label><input name="longitude" type="number" step="any" class="form-control" value="{{ old('longitude', $editing?->longitude) }}"></div></div>
                <div class="schedule-block mx-4 mb-4"><h3>Standard operating hours</h3><p class="text-muted small">Enter verified hours for each day, or use “Closed”.</p><div class="row g-2">@foreach($days as $day)<div class="col-sm-6 col-lg-4"><label class="form-label small text-capitalize">{{ $day }}</label><input name="working_hours[{{ $day }}]" class="form-control form-control-sm" value="{{ $workingHours[$day] ?? '' }}" placeholder="9:00 AM - 5:00 PM"></div>@endforeach</div></div>
                <div class="hotline-block mx-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><div><h3 class="mb-1">Regional hotlines</h3><p class="text-muted small mb-0">Add every verified number serving this location.</p></div><button type="button" id="add-hotline" class="btn btn-sm btn-outline-dark"><i class="fas fa-plus me-1"></i>Add hotline</button></div><div id="hotlines">@foreach($formHotlines as $index => $hotline)<div class="hotline-row row g-2 align-items-end mb-3"><div class="col-md-3"><label class="form-label small">Name</label><input name="hotlines[{{ $index }}][name]" class="form-control" value="{{ $hotline['name'] ?? '' }}" placeholder="Crisis line"></div><div class="col-md-3"><label class="form-label small">Phone number</label><input name="hotlines[{{ $index }}][phone_number]" class="form-control" value="{{ $hotline['phone_number'] ?? '' }}" placeholder="+880..."></div><div class="col-md-2"><label class="form-label small">Hours</label><input name="hotlines[{{ $index }}][operating_hours][all]" class="form-control" value="{{ $hotline['operating_hours']['all'] ?? '' }}" placeholder="24/7"></div><div class="col-md-2"><label class="form-label small">Description</label><input name="hotlines[{{ $index }}][description]" class="form-control" value="{{ $hotline['description'] ?? '' }}"></div><div class="col-md-1"><div class="form-check"><input class="form-check-input" type="checkbox" name="hotlines[{{ $index }}][is_toll_free]" value="1" @checked(!empty($hotline['is_toll_free']))><label class="form-check-label small">Free</label></div></div><div class="col-md-1"><button type="button" class="btn btn-sm btn-outline-danger remove-hotline" title="Remove hotline"><i class="fas fa-trash"></i></button></div></div>@endforeach</div></div>
                <div class="form-footer"><button class="btn btn-crimson" type="submit"><i class="fas fa-check me-2"></i>{{ $isEditing ? 'Save changes' : 'Register help-center' }}</button></div>
            </form>
        </section>
    </div>
</div>

<style>
.directory-page{background:#f7f4f1;min-height:calc(100vh - 72px);color:#20242b}.directory-hero{min-height:350px;background-image:url('https://st2.depositphotos.com/16122460/44465/i/450/depositphotos_444658674-stock-photo-closeup-view-woman-holding-red.jpg');background-size:cover;background-position:center}.hero-overlay{min-height:350px;background:linear-gradient(90deg,rgba(21,26,31,.88),rgba(21,26,31,.36));display:flex;align-items:center;color:#fff}.hero-overlay h1{max-width:720px;font-size:clamp(2rem,4vw,3.7rem);font-weight:800;line-height:1.05;margin:8px 0 14px}.hero-overlay p:not(.eyebrow){max-width:620px;font-size:17px;margin-bottom:24px}.eyebrow{color:#b21e3b;text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:800}.hero-overlay .eyebrow{color:#f1b3bf}.btn-crimson{background:#b21e3b;color:#fff;border:0}.btn-crimson:hover{background:#8f1730;color:#fff}.location-card,.form-panel{background:#fff;border:1px solid #e8e0db;box-shadow:0 4px 16px #30231b0b}.location-card{padding:20px}.location-card h3{font-size:19px;margin:7px 0 16px}.type-label{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#b21e3b;font-weight:800}.status-dot{width:10px;height:10px;background:#38855c;border-radius:50%;margin-top:7px}.address{font-size:13px;color:#61656b;min-height:42px}.hotline-list{border-top:1px solid #eee6e0;padding-top:12px;font-size:13px;min-height:48px}.hotline-list>div{margin-bottom:5px}.mini-tag{font-size:10px;background:#e2f1e7;color:#267050;padding:3px 5px;margin-left:7px}.card-actions{border-top:1px solid #eee6e0;padding-top:14px;margin-top:14px;display:flex;gap:8px}.empty-state{background:#fff;border:1px dashed #cfc5be;text-align:center;padding:34px;color:#777}.form-panel{margin-bottom:45px}.panel-heading{padding:20px;border-bottom:1px solid #eee6e0;display:flex;justify-content:space-between;align-items:center}.form-note{background:#eef5f4;border-left:3px solid #367d76;padding:10px 12px;color:#2b5d59;font-size:13px}.schedule-block,.hotline-block{background:#faf8f6;border:1px solid #eee6e0;padding:18px}.schedule-block h3,.hotline-block h3{font-size:16px}.form-footer{border-top:1px solid #eee6e0;padding:18px 20px;text-align:right}
</style>
<script>
document.addEventListener('DOMContentLoaded', () => { const list=document.getElementById('hotlines'); const add=document.getElementById('add-hotline'); let index=list.querySelectorAll('.hotline-row').length; add.addEventListener('click',()=>{ const row=document.createElement('div'); row.className='hotline-row row g-2 align-items-end mb-3'; row.innerHTML=`<div class="col-md-3"><label class="form-label small">Name</label><input name="hotlines[${index}][name]" class="form-control" placeholder="Crisis line"></div><div class="col-md-3"><label class="form-label small">Phone number</label><input name="hotlines[${index}][phone_number]" class="form-control" placeholder="+880..." required></div><div class="col-md-2"><label class="form-label small">Hours</label><input name="hotlines[${index}][operating_hours][all]" class="form-control" placeholder="24/7"></div><div class="col-md-2"><label class="form-label small">Description</label><input name="hotlines[${index}][description]" class="form-control"></div><div class="col-md-1"><div class="form-check"><input class="form-check-input" type="checkbox" name="hotlines[${index}][is_toll_free]" value="1"><label class="form-check-label small">Free</label></div></div><div class="col-md-1"><button type="button" class="btn btn-sm btn-outline-danger remove-hotline"><i class="fas fa-trash"></i></button></div>`; list.appendChild(row); index++; }); list.addEventListener('click', event => { const button=event.target.closest('.remove-hotline'); if(button && list.querySelectorAll('.hotline-row').length>1) button.closest('.hotline-row').remove(); }); });
</script>
@endsection
